package:
  name: "pyscf"
  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ..

build:
  number: 0

requirements:
  build:
    - python {{ python }}
    - cmake
    - make
    - mkl
    - scikit-build-core
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
  run:
    - python
    - mkl
    - numpy>=1.13
    - scipy!=1.5
    - h5py>=2.7

test:
  imports:
    - pyscf.lib

about:
  home: "http://www.pyscf.org"
  license: "Apache-2.0"
  summary: "PySCF: Python-based Simulations of Chemistry Framework"
