{% set version_match = load_file_regex(
  load_file="pyscf/_version.py",
  regex_pattern='(?i)^__version__ = [\'"]v?(.+)[\'"]') %}
{% set version = version_match[1] %}

package:
  name: pyscf
  version: {{ version }}

source:
  path: ..

build:
  number: 0

requirements:
  build:
    - python {{ python }}
    - cmake
    - make
    - mkl
    - scikit-build-core
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - llvm-openmp # [osx]
    - libgomp # [linux]
  host:
    - python
    - scikit-build-core
  run:
    - python
    - mkl
    - numpy>=1.13
    - scipy!=1.5
    - h5py>=2.7

test:
  imports:
    - pyscf.lib

about:
  home: https://www.pyscf.org
  dev_url: https://github.com/pyscf/pyscf
  doc_url: https://www.pyscf.org
  license: Apache-2.0
  license_file: LICENSE
  summary: "PySCF: Python-based Simulations of Chemistry Framework"
