{% set data = load_setup_py_data() %}
{% set project_data = load_file_data('pyproject.toml')['project'] %}
{% set build = 0 %}

package:
  name: "pyscf"
  version: "{{ data['version'] }}"

source:
  path: ..

build:
  number: {{ build }} # [not (linux and x86_64)]
  number: {{ build + 100 }} # [linux and x86_64 and microarch_level == 1]
  number: {{ build + 200 }} # [linux and x86_64 and microarch_level == 2]
  number: {{ build + 300 }} # [linux and x86_64 and microarch_level == 3]
  number: {{ build + 400 }} # [linux and x86_64 and microarch_level == 4]

requirements:
  build:
    - python {{ python }}
    - cmake
    - make
    - mkl
    - x86_64-microarch-level {{ microarch_level }} # [linux and x86_64]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
  host:
    - python
  run:
    - python
    - mkl
    - libblas=*=*mkl
    - numpy>=1.13
    - scipy!=1.5
    - h5py>=2.7

test:
  imports:
    - pyscf.lib

about:
  home: "{{ project_data['urls']['Homepage'] }}"
  license: "{{ project_data['license'] }}"
  summary: "{{ project_data['description'] }}"
