#!/usr/bin/env bash

cmake -B build -S . \
	-DCMAKE_BUILD_TYPE=Release \
	-DBUILD_MARCH_NATIVE=ON \
	-DENABLE_VECTOR_MATH=ON \
	-DFORCE_INTEL_OPENMP=ON \
	-DENABLE_LIBXC=ON \
	-DENABLE_XCFUN=OFF \
	-DBUILD_LIBXC=OFF \
	-DBUILD_XCFUN=OFF \
	-DUSE_QCINT=ON \
	-DENABLE_MKL=ON \
	-DENABLE_FFTW=OFF \
	-DBLA_VENDOR=Intel10_64_dyn \
	-DENABLE_IPO=OFF \
	-G Ninja
